name: Update versions registry

on:
  pull_request:
    types: [closed]

jobs:

  update_registry:
    name: Update versions registry
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0  # fetch all history
      
      - name: Get plugin name
        id: get_plugin_name
        run: |
          echo "plugin_name=$(git diff --name-only HEAD HEAD~1 | grep -m1 "" | cut -d'/' -f2)" >> $GITHUB_OUTPUT

      - name: Get plugin version
        id: get_plugin_version
        run: |
          echo "plugin_version=$(jq -c . < ./plugins/${{ steps.get_plugin_name.outputs.plugin_name }}/plugin.json | jq -r .version)" >> $GITHUB_OUTPUT
      
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Update versions registry
        id: update_registry
        run: |
          node ./scripts/updateRegistry.js ${{ steps.get_plugin_name.outputs.plugin_name }} ${{ steps.get_plugin_version.outputs.plugin_version }} ${{ github.event.pull_request.head.sha }}
          cat ./versions.json
      